import type { Order } from './types'

export const mockOrders: Order[] = [
  {
    id: 1,
    customer_name: 'Maria Santos',
    email: 'maria@email.com',
    phone_number: '555-0101',
    pickup_datetime: '2025-12-25T18:30:00',
    items: [
      { id: 1, food_name: 'Adobo', quantity: 2, size: 'Regular', price: 285.0 },
      { id: 2, food_name: 'Lumpia', quantity: 1, size: 'Half Tray', price: 145.0 },
    ],
    subtotal: 715.0,
    store_id: 'Location 1',
    status: 'active',
  },
  {
    id: 2,
    customer_name: 'Juan Dela Cruz',
    email: 'juan@email.com',
    phone_number: '555-0102',
    pickup_datetime: '2025-12-25T19:00:00',
    items: [
      { id: 1, food_name: 'Sinigang', quantity: 1, size: 'Large', price: 295.0 },
      { id: 2, food_name: 'Halo-Halo', quantity: 2, size: 'Large', price: 95.0 },
    ],
    subtotal: 485.0,
    store_id: 'Location 2',
    status: 'completed',
  },
  {
    id: 3,
    customer_name: 'Rosa Diaz',
    phone_number: '555-0103',
    pickup_datetime: '2025-12-25T17:45:00',
    items: [
      { id: 1, food_name: 'Kare-Kare', quantity: 1, size: 'Regular', price: 320.0 },
      { id: 2, food_name: 'Laing', quantity: 2, size: 'Regular', price: 185.0 },
    ],
    subtotal: 690.0,
    store_id: 'Location 1',
    status: 'packed',
  },
  {
    id: 4,
    customer_name: 'Pedro Gonzales',
    email: 'pedro@email.com',
    phone_number: '555-0104',
    pickup_datetime: '2026-01-01T20:15:00',
    items: [
      { id: 1, food_name: 'Lechon Paksiw', quantity: 1, size: 'Large', price: 350.0 },
    ],
    subtotal: 350.0,
    store_id: 'Location 2',
    status: 'active',
  },
  {
    id: 5,
    customer_name: 'Lucia Fernandez',
    phone_number: '555-0105',
    pickup_datetime: '2026-01-01T18:00:00',
    items: [
      { id: 1, food_name: 'Ube Cake', quantity: 3, size: 'Slice', price: 75.0 },
      { id: 2, food_name: 'Halo-Halo', quantity: 2, size: 'Small', price: 95.0 },
    ],
    subtotal: 415.0,
    store_id: 'Location 1',
    status: 'completed',
  },
  {
    id: 6,
    customer_name: 'Carlos Rodriguez',
    email: 'carlos@email.com',
    phone_number: '555-0106',
    pickup_datetime: '2026-01-01T19:30:00',
    items: [
      { id: 1, food_name: 'Adobo', quantity: 1, size: 'Large', price: 285.0 },
      { id: 2, food_name: 'Kare-Kare', quantity: 2, size: 'Regular', price: 320.0 },
      { id: 3, food_name: 'Lumpia', quantity: 2, size: 'Full Tray', price: 145.0 },
    ],
    subtotal: 895.0,
    store_id: 'Location 2',
    status: 'packed',
  },
  {
    id: 7,
    customer_name: 'Angela Torres',
    email: 'angela@email.com',
    phone_number: '555-0107',
    pickup_datetime: '2026-01-01T17:00:00',
    items: [
      { id: 1, food_name: 'Adobo', quantity: 2, size: 'Large', price: 285.0 },
      { id: 2, food_name: 'Sinigang', quantity: 2, size: 'Large', price: 295.0 },
      { id: 3, food_name: 'Kare-Kare', quantity: 2, size: 'Regular', price: 320.0 },
      { id: 4, food_name: 'Laing', quantity: 1, size: 'Regular', price: 185.0 },
      { id: 5, food_name: 'Lumpia', quantity: 2, size: 'Full Tray', price: 145.0 },
      { id: 6, food_name: 'Lechon Paksiw', quantity: 1, size: 'Large', price: 350.0 },
      { id: 7, food_name: 'Halo-Halo', quantity: 4, size: 'Large', price: 95.0 },
      { id: 8, food_name: 'Ube Cake', quantity: 2, size: 'Slice', price: 75.0 },
      { id: 9, food_name: 'Pancit', quantity: 1, size: 'Large', price: 240.0 },
      { id: 10, food_name: 'Bibingka', quantity: 3, size: 'Regular', price: 55.0 },
    ],
    subtotal: 3245.0,
    store_id: 'Location 1',
    status: 'active',
  },
]
